name: ci

on:
  pull_request:
    branches:
      - main

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22.4'
      - name: フォーマットを実行
        run: test -z $(gofmt -l .)
      - name: 静的解析を実行
        run: go vet ./...
      - run: go test
      - run: go build .